defaults: &defaults
  environment:
    CONTAINER_PREFIX: planet4-colombia
  docker:
    - image: gcr.io/planet-4-151612/p4-builder:latest
  working_directory:  /home/circleci

version: 2

job_descriptions:
  build_steps: &build_steps
    steps:
      - setup_remote_docker
      - run: activate-gcloud-account.sh
      - run: mkdir -p /tmp/workspace/var
      - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: make
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Build" notify-job-failure.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
  deploy_steps: &deploy_steps
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: activate-gcloud-account.sh
      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make -j2 deploy

jobs:
  build-branch:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet-4-151612
    <<: *build_steps

  build-release:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    <<: *build_steps

  build-tag:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    <<: *build_steps


  deploy-develop:
    <<: *defaults
    environment:
      APP_ENVIRONMENT: development
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: colombia
      CLOUDSQL_INSTANCE: p4-develop-k8s
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      NEWRELIC_APPNAME: P4 Colombia Development
      WP_DB_NAME: planet4-colombia_wordpress_develop
      WP_STATELESS_BUCKET: planet4-colombia-stateless-develop
    <<: *deploy_steps

  deploy-release:
    <<: *defaults
    environment:
      APP_ENVIRONMENT: staging
      APP_HOSTNAME: release.k8s.p4.greenpeace.org
      APP_HOSTPATH: colombia
      CLOUDSQL_INSTANCE: planet4-prod
      GCLOUD_CLUSTER: planet4-production
      GOOGLE_PROJECT_ID: planet4-production
      HELM_NAMESPACE: colombia
      HELM_RELEASE: planet4-colombia-release
      NEWRELIC_APPNAME: P4 Colombia Release
      WP_DB_NAME: planet4-colombia_wordpress_release
      WP_STATELESS_BUCKET: planet4-colombia-stateless-release
    <<: *deploy_steps

  deploy-tag:
    <<: *defaults
    environment:
      APP_HOSTNAME: master.k8s.p4.greenpeace.org
      APP_HOSTPATH: colombia
      CLOUDSQL_INSTANCE: planet4-prod
      GCLOUD_CLUSTER: planet4-production
      GOOGLE_PROJECT_ID: planet4-production
      HELM_NAMESPACE: colombia
      HELM_RELEASE: planet4-colombia-master
      MIN_REPLICA_COUNT: 2
      NEWRELIC_APPNAME: P4 Colombia Production
      WP_DB_NAME: planet4-colombia_wordpress_master
      WP_STATELESS_BUCKET: planet4-colombia-stateless
    <<: *deploy_steps

workflows:
  version: 2
  develop:
    jobs:
    - build-branch:
        context: org-global
        filters:
          branches:
            only: develop
    - deploy-develop:
        context: org-global
        requires:
          - build-branch
        filters:
          branches:
            only: develop

  release:
    jobs:
    - build-release:
        context: org-global
        filters:
          branches:
            only: /^release.*/
    - deploy-release:
        context: org-global
        requires:
          - build-release
        filters:
          branches:
            only: /^release.*/
  tag:
    jobs:
      - build-tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - hold-tag:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - build-tag
      - deploy-tag:
          context: org-global
          requires:
            - hold-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
